[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"

# Configure secrets scanning to ignore VITE_ environment variables
# These are meant to be public in Vite applications
[secrets_scanning]
  enabled = true
  omit_keys = [
    "VITE_SUPABASE_URL",
    "VITE_SUPABASE_ANON_KEY", 
    "VITE_CLAUDE_API_KEY"
  ]

# Redirect rules for SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
